### ISSUE TITLE
Order Icon should available for RMA order status

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/track-orders-for-woocommerce#32]
**WooCommerce - 9.1.4
Wordpress - 6.6.1
Plugin Version - 1.0.5
Description -** Order Icon should available for RMA order status

![image](https://github.com/user-attachments/assets/57e6b2fe-9e04-48eb-890d-4bf9ebdff449)

**Comment by prince-cedcoss** [comment]
isse is fixed now

**Comment by ashish-wps** [comment]
Fixed
