### ISSUE TITLE
Warning shown on templates

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/track-orders-for-woocommerce#33]
**WooCommerce - 9.1.4
Wordpress - 6.6.1
Plugin Version - 1.0.5
Description -** Warning shown on templates and amount value show 0

![image](https://github.com/user-attachments/assets/59799333-5b3a-41be-8380-b73d763b319d)

![image](https://github.com/user-attachments/assets/9040c424-1493-4bd1-a56e-ead02607cb0c)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by ashish-wps** [comment]
Fixed
