### ISSUE TITLE
Please remove extra dual tracking link

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/track-orders-for-woocommerce#34]
**WooCommerce - 9.1.4
Wordpress - 6.6.1
Plugin Version - 1.0.5
Description -** Please remove extra dual tracking link

![image](https://github.com/user-attachments/assets/17efac5b-cc1e-45b6-ac18-2e4637535a90)

**Comment by prince-cedcoss** [comment]
This tracking link is for the third-party API link like Canada post or FedEx or something like that.
so, it is part of a feature.

**Comment by ashish-wps** [comment]
Okay
