### ISSUE TITLE
The documentation section does not reach the proper documentation section.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/track-orders-for-woocommerce#35]
WooCommerce - 9.3.2
WordPress - 6.6.2
Plugin Version - ORG
Description -                  The documentation section does not reach the proper documentation section.

[scrnli_25_09_2024_12-29-33.webm](https://github.com/user-attachments/assets/58163abb-8682-4442-9da4-af92d8cba192)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
