### ISSUE TITLE
Waring shown on Track order page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/track-orders-for-woocommerce#36]
**WooCommerce - 9.4.1
Wordpress - 6.7.1
Plugin Version - 1.0.9
Description -**  Waring shown on Track order page

![image](https://github.com/user-attachments/assets/e0bddb67-86db-4968-bf78-99e825f4ea01)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by ashish-wps** [comment]
Fixed
