### ISSUE TITLE
Pro plugin templates shown in ORG plugin

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/track-orders-for-woocommerce#37]
**WooCommerce - 9.4.1
Wordpress - 6.7.1
Plugin Version - 1.0.9
Description -**  Pro plugin templates shown in ORG plugin

[scrnli_6TAtF3Ex3ViIln.webm](https://github.com/user-attachments/assets/c9f955c8-0db7-46e8-895f-15ee35f9d6dc)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by ashish-wps** [comment]
fixed
