### ISSUE TITLE
The template status displays as "Not set," even though the admin has already configured it as Template 2.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/track-orders-for-woocommerce#38]
**WooCommerce - 9.4.1
Wordpress - 6.7.1
Plugin Version - 1.0.9
Description -** The template status displays as "Not set," even though the admin has already configured it as Template 2.

![image](https://github.com/user-attachments/assets/7fd552af-4c89-4106-be8c-bb86d5bb4d9b)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by ashish-wps** [comment]
Fixed
