### ISSUE TITLE
An edit option should be available for Custom Templates.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/track-orders-for-woocommerce#39]
**WooCommerce - 9.4.1
Wordpress - 6.7.1
Plugin Version - 1.0.9
Description -** An edit option should be available for Custom Templates.

![image](https://github.com/user-attachments/assets/7fd552af-4c89-4106-be8c-bb86d5bb4d9b)

**Comment by prince-cedcoss** [comment]
implementation is done now

**Comment by ashish-wps** [comment]
Fixed
